#######################
# Theme Customization #
#######################

title: Debbie's website                             # used in <title> tag & site header
author: 蔡力争                        # used in a <meta> tag & /feed.xml
description: >                              # used in a <meta> tag & /feed.xml
  保持对所做之事的适度渴望，是一切方法得以实施的前提
slogan: Showtime!                           # used in site header, beside title
avatar: /i/avatar.png                       # used as portrait in site header
banner: /i/mountains.svg                    # used as background in site header
url: http://solana.ryanlue.com              # used by plugins to generate feed.xml and sitemap.xml
baseurl: ''                                 # prepended to all absolute filepaths
repo: https://github.com/rlue/jekyll-solana # used in footer

# Objects listed here will appear in the main nav menu.
# Exceeding four items may cause problems on the desktop (>900px wide) layout.
nav_menu:
  - name: 网页设计作品集
    url: Debbie925.github.io/portfolio/index.html
    icon: /i/icons.svg#posts # icons should be 24x24 px.
  - name: 信息可视化作品集
    url: /Debbie925.github.io/infovis/index.html
    icon: /i/icons.svg#portfolio
  - name: web学习笔记
    url: /projects
    icon: /i/icons.svg#github
    outbound: true      # this key sets a link to open in a new window.
  - name: 信息可视化笔记
    url:  Debbie925.github.io/posts/infovis/   # these keys enable email obfuscation.
    icon: /i/icons.svg#email     # you know, to protect you from bots. (handle and domain
    outbound: true  # are separated in case bots crawl GitHub repos, too.)
    

# Objects listed here will appear on the /projects.html page.
projects:
  - title: 如何显示水平分割线
    teaser: 如何建立一个水平分割线
    url: https://debbie925.github.io/posts/rwd/2017-01-02-C
    role: Debbie
    category: RWD
  - title: CSS3的动画
    teaser: 关于CSS的动画
    url: https://debbie925.github.io/posts/rwd/2018-01-01-D
    role: Debbie
    category: RWD
  - title: Rihanna
    teaser: Possibly another robot. Also available on Google Play.
    url: https://play.google.com/store/music/artist/Rihanna?id=Arcw2m2ih45qntv3fufub25tyhu
    role: Contributor
    category: Algorithmic Composition

#################
# Site Settings #
#################

incremental: true
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - TODO.md

permalink: /:collection/:path

collections:
  category: { output: true }
  tag:      { output: true }

defaults:
  - scope:  { type:   posts    }
    values: { layout: post     }
  - scope:  { type:   tag      }
    values: { layout: listing  }
  - scope:  { type:   category }
    values: { layout: listing  }

sass:
  sass_dir: _assets/css

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

paginate: 10
